#!/bin/bash

# DHS Health Records Contract Deployment Script
# This script automates the deployment process to Stellar Testnet

set -e

echo "🚀 DHS Health Records Contract Deployment"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
NETWORK="testnet"
IDENTITY="alice"
RPC_URL="https://soroban-testnet.stellar.org:443"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

# Step 1: Check prerequisites
echo "📋 Step 1: Checking prerequisites..."

if ! command -v soroban &> /dev/null; then
    echo -e "${RED}❌ Soroban CLI not found. Please install it first.${NC}"
    echo "Run: cargo install --locked soroban-cli --features opt"
    exit 1
fi

if ! command -v cargo &> /dev/null; then
    echo -e "${RED}❌ Cargo not found. Please install Rust first.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Prerequisites check passed${NC}"
echo ""

# Step 2: Setup network
echo "🌐 Step 2: Setting up Stellar Testnet..."

# Check if network exists, if not add it
if ! soroban network ls | grep -q "testnet"; then
    echo "Adding testnet network..."
    soroban network add \
      --global testnet \
      --rpc-url $RPC_URL \
      --network-passphrase "$NETWORK_PASSPHRASE"
fi

echo -e "${GREEN}✅ Network configured${NC}"
echo ""

# Step 3: Setup identity
echo "🔑 Step 3: Setting up identity..."

# Check if identity exists
if ! soroban keys ls | grep -q "$IDENTITY"; then
    echo "Generating new identity: $IDENTITY"
    soroban keys generate --global $IDENTITY --network $NETWORK
    
    # Fund the account
    echo "Funding account from Friendbot..."
    ACCOUNT_ADDRESS=$(soroban keys address $IDENTITY)
    curl -s "https://friendbot.stellar.org?addr=$ACCOUNT_ADDRESS" > /dev/null
    sleep 2
else
    ACCOUNT_ADDRESS=$(soroban keys address $IDENTITY)
    echo "Using existing identity: $IDENTITY"
    echo "Address: $ACCOUNT_ADDRESS"
fi

echo -e "${GREEN}✅ Identity ready${NC}"
echo ""

# Step 4: Build contract
echo "🔨 Step 4: Building contract..."

cargo build --target wasm32-unknown-unknown --release

if [ ! -f "target/wasm32-unknown-unknown/release/dhs_health_records.wasm" ]; then
    echo -e "${RED}❌ Build failed. WASM file not found.${NC}"
    exit 1
fi

WASM_SIZE=$(du -h target/wasm32-unknown-unknown/release/dhs_health_records.wasm | cut -f1)
echo -e "${GREEN}✅ Contract built successfully (Size: $WASM_SIZE)${NC}"
echo ""

# Step 5: Deploy contract
echo "🚀 Step 5: Deploying contract to Testnet..."

CONTRACT_ID=$(soroban contract deploy \
  --wasm target/wasm32-unknown-unknown/release/dhs_health_records.wasm \
  --source $IDENTITY \
  --network $NETWORK)

if [ -z "$CONTRACT_ID" ]; then
    echo -e "${RED}❌ Deployment failed${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Contract deployed successfully!${NC}"
echo ""
echo "📝 Contract ID: $CONTRACT_ID"
echo ""

# Step 6: Initialize contract
echo "⚙️  Step 6: Initializing contract..."

soroban contract invoke \
  --id $CONTRACT_ID \
  --source $IDENTITY \
  --network $NETWORK \
  -- \
  initialize \
  --admin $ACCOUNT_ADDRESS

echo -e "${GREEN}✅ Contract initialized${NC}"
echo ""

# Step 7: Verify deployment
echo "✅ Step 7: Verifying deployment..."

ADMIN=$(soroban contract invoke \
  --id $CONTRACT_ID \
  --source $IDENTITY \
  --network $NETWORK \
  -- \
  get_admin)

TOTAL_RECORDS=$(soroban contract invoke \
  --id $CONTRACT_ID \
  --source $IDENTITY \
  --network $NETWORK \
  -- \
  get_total_records)

echo "Admin Address: $ADMIN"
echo "Total Records: $TOTAL_RECORDS"
echo ""

# Step 8: Save deployment info
echo "💾 Step 8: Saving deployment information..."

cat > deployment-info.json <<EOF
{
  "network": "$NETWORK",
  "contractId": "$CONTRACT_ID",
  "adminAddress": "$ACCOUNT_ADDRESS",
  "rpcUrl": "$RPC_URL",
  "networkPassphrase": "$NETWORK_PASSPHRASE",
  "deployedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "wasmSize": "$WASM_SIZE"
}
EOF

echo -e "${GREEN}✅ Deployment info saved to deployment-info.json${NC}"
echo ""

# Step 9: Generate frontend config
echo "⚛️  Step 9: Generating frontend configuration..."

cat > ../../src/config/contract.js <<EOF
// DHS Health Records Contract Configuration
// Auto-generated by deploy.sh

export const CONTRACT_CONFIG = {
  // Contract ID on Stellar Testnet
  contractId: '$CONTRACT_ID',
  
  // Network configuration
  network: '$NETWORK',
  rpcUrl: '$RPC_URL',
  networkPassphrase: '$NETWORK_PASSPHRASE',
  
  // Admin address
  adminAddress: '$ACCOUNT_ADDRESS',
  
  // Token configuration
  tokenDecimals: 7,
  uploadReward: 10, // DHS tokens per upload
  
  // Deployment metadata
  deployedAt: '$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
};

// Function names for contract calls
export const CONTRACT_FUNCTIONS = {
  // Core functions
  ADD_RECORD: 'add_record',
  GET_RECORDS: 'get_records',
  GET_RECORD_BY_INDEX: 'get_record_by_index',
  GET_RECORD_COUNT: 'get_record_count',
  
  // Token functions
  GET_BALANCE: 'get_balance',
  TRANSFER: 'transfer',
  
  // Admin functions
  GET_TOTAL_RECORDS: 'get_total_records',
  GET_ADMIN: 'get_admin',
};
EOF

echo -e "${GREEN}✅ Frontend config generated at src/config/contract.js${NC}"
echo ""

# Final summary
echo "=========================================="
echo "🎉 Deployment Complete!"
echo "=========================================="
echo ""
echo "📋 Summary:"
echo "  • Network: $NETWORK"
echo "  • Contract ID: $CONTRACT_ID"
echo "  • Admin Address: $ACCOUNT_ADDRESS"
echo "  • WASM Size: $WASM_SIZE"
echo ""
echo "🔗 Useful Links:"
echo "  • Stellar Expert: https://stellar.expert/explorer/testnet/contract/$CONTRACT_ID"
echo "  • RPC Endpoint: $RPC_URL"
echo ""
echo "📝 Next Steps:"
echo "  1. Update your frontend with the contract ID"
echo "  2. Test contract functions using the CLI or frontend"
echo "  3. Monitor transactions on Stellar Expert"
echo ""
echo "💡 Quick Test:"
echo "  soroban contract invoke \\"
echo "    --id $CONTRACT_ID \\"
echo "    --source $IDENTITY \\"
echo "    --network $NETWORK \\"
echo "    -- \\"
echo "    get_total_records"
echo ""
echo -e "${GREEN}Happy building! 🚀${NC}"
